`timescale 1ns / 1ps

module tb_exhaustive_decoder();

    // --------------------------------------------------------
    // 1. Inputs to UUT
    // --------------------------------------------------------
    reg [127:0] cache_line;

    // --------------------------------------------------------
    // 2. Outputs from UUT
    // --------------------------------------------------------
    wire prefix_rep;
    wire prefix_op_size;
    wire [2:0] prefix_seg_ov_id;
    wire prefix_ext;
    wire [7:0] opcode;
    wire [7:0] modrm;
    wire modrm_v;
    wire [7:0] sib;
    wire [1:0] disp_size_mux;
    wire [31:0] disp;
    wire [1:0] imm_size;
    wire [47:0] imm;
    wire [1:0] addressing_mode;
    wire [3:0] instr_length;

    // --------------------------------------------------------
    // 3. Instantiate UUT (block_decoder)
    // --------------------------------------------------------
    block_decoder uut (
        .cache_line(cache_line),
        .prefix_rep(prefix_rep),
        .prefix_op_size(prefix_op_size),
        .prefix_seg_ov_id(prefix_seg_ov_id),
        .prefix_ext(prefix_ext),
        .opcode(opcode),
        .modrm(modrm),
        .modrm_v(modrm_v),
        .sib(sib),
        .disp_size_mux(disp_size_mux),
        .disp(disp),
        .imm_size(imm_size),
        .imm(imm),
        .addressing_mode(addressing_mode),
        .instr_length(instr_length)
    );

    // --------------------------------------------------------
    // 4. File I/O and Test Tracking Variables
    // --------------------------------------------------------
    integer file, r, i;
    
    // The 8 Expected Outputs from the Python File
    reg [3:0] exp_len;
    reg exp_opsize, exp_rep, exp_ext, exp_modrm_v;
    reg [7:0] exp_opcode, exp_modrm, exp_sib;
    
    // Array to hold the 16 bytes read from file
    reg [7:0] b [0:15]; 

    integer test_count = 0;
    integer FAILURES = 0;
    integer SUCCESSES = 0;

    // --------------------------------------------------------
    // 5. Main Test Loop
    // --------------------------------------------------------
    initial begin
        $dumpfile("exhaustive_decoder_tb.vpd");
        $dumpvars(0, tb_exhaustive_decoder);

        $display("========================================");
        $display("  STARTING PILLAR 1 EXHAUSTIVE SWEEP    ");
        $display("========================================");
        
        // Open the file generated by the expanded Python script
        file = $fopen("pillar1_tests.hex", "r");
        if (file == 0) begin
            $display("❌ ERROR: Could not open pillar1_tests.hex!");
            $display("Make sure you ran the Python script first and the file is in the simulation directory.");
            $finish;
        end

        // Loop until end of file
        while (!$feof(file)) begin
            // Read 24 hex values per line (8 expected vals + 16 cache line bytes)
            r = $fscanf(file, "%x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x\n",
                        exp_len, exp_opsize, exp_rep, exp_ext, exp_opcode, exp_modrm_v, exp_modrm, exp_sib,
                        b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7],
                        b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15]);

            // Only process if we successfully read a full line (avoids blank line errors at EOF)
            if (r > 0) begin
                // Pack the array of bytes into the 128-bit cache_line vector.
                for (i = 0; i < 16; i = i + 1) begin
                    cache_line[(i*8) +: 8] = b[i];
                end

                #15; // Wait 15ns for the combinational decoder logic to fully settle
                
                test_count = test_count + 1;

                // Self-Checking Assertions
                if (instr_length !== exp_len || 
                    opcode !== exp_opcode || 
                    modrm_v !== exp_modrm_v || 
                    (exp_modrm_v && modrm !== exp_modrm) || 
                    prefix_op_size !== exp_opsize || 
                    prefix_rep !== exp_rep ||
                    prefix_ext !== exp_ext) begin
                    
                    $display("❌ FAIL [Test %0d]", test_count);
                    $display("   EXPECTED: Len=%0d OpSize=%b Rep=%b Ext=%b Op=%h ModV=%b ModRM=%h", 
                             exp_len, exp_opsize, exp_rep, exp_ext, exp_opcode, exp_modrm_v, exp_modrm);
                    $display("   ACTUAL  : Len=%0d OpSize=%b Rep=%b Ext=%b Op=%h ModV=%b ModRM=%h", 
                             instr_length, prefix_op_size, prefix_rep, prefix_ext, opcode, modrm_v, modrm);
                    $display("   DEBUG   : disp_size_mux=%b, imm_size=%b, sib=%h", disp_size_mux, imm_size, sib);
                    FAILURES = FAILURES + 1;
                end
                else begin
                    // Optional: Comment this out if 500+ lines of "PASS" clutters your console too much
                    $display("✅ PASS [Test %0d]", test_count);
                    SUCCESSES = SUCCESSES + 1;
                end
            end
        end

        $fclose(file);
        
        $display("========================================");
        $display("        EXHAUSTIVE SWEEP COMPLETE       ");
        $display("  Ran %0d tests.", test_count);
        if (FAILURES == 0) begin
            $display("  ✅ ALL TESTS PASSED! ZERO FAILURES!");
        end else begin
            $display("  ❌ FAILED %0d TESTS.", FAILURES);
        end
        $display("========================================");
        $display("FAILURES = %d out of %d", FAILURES, FAILURES + SUCCESSES);
        $display("SUCCESSES = %d out of %d\n", SUCCESSES, FAILURES + SUCCESSES);
        $finish;
    end

endmodule