module we_logic_block #(
  parameter   RANK_BIT_WIDTH=128,
  parameter   BUS_BIT_WIDTH=32,
  parameter   RANK_BURST_SIZE=4,
  parameter   MEM_ADDR_WIDTH=15,
  parameter   NUM_SETS=8,
  parameter   INDEX_WIDTH=$clog2(NUM_SETS),
  parameter   NUM_WAYS=4,
  parameter   WAY_WIDTH=$clog2(NUM_WAYS)
) (           
  input     [MEM_ADDR_WIDTH-1:RANK_BURST_SIZE]      ICACHE_PHYS_ADDR,
  input     [WAY_WIDTH-1:0]                         ICACHE_VICT_WAY,

  output    [NUM_SETS*NUM_WAYS*RANK_BURST_SIZE-1:0] DATA_WR_MASK_OUT,
  output    [NUM_SETS*NUM_WAYS*RANK_BURST_SIZE-1:0] SB_DATA_WR_MASK_OUT,

  output    [INDEX_WIDTH-1:0]                       TAG_VALID_SET_INDEX,
  output    [NUM_WAYS-1:0]                          TAG_WR_MASK_OUT,

  output    [INDEX_WIDTH+WAY_WIDTH-1:0]             VALID_WR_EN
);

wire [NUM_SETS*NUM_WAYS*RANK_BURST_SIZE-1:0] DATA_WR_MASK_OUT_UNINVERTED, SB_DATA_WR_MASK_OUT_UNINVERTED;

lshf_chunks_var_128b #(.SHF_ZEROS(1))
lshf_chunks_var_128b_DATA_WR_MASK_OUT_UNINVERTED(
  .in(128'd1),
  .shf_amt({ICACHE_PHYS_ADDR[RANK_BURST_SIZE+INDEX_WIDTH-1:RANK_BURST_SIZE], ICACHE_VICT_WAY}),
  .out(DATA_WR_MASK_OUT_UNINVERTED)
);

lshf_chunks_var_128b #(.SHF_ZEROS(1))
lshf_chunks_var_128b_SB_DATA_WR_MASK_OUT_UNINVERTED(
  .in(128'd15),
  .shf_amt({ICACHE_PHYS_ADDR[RANK_BURST_SIZE+INDEX_WIDTH-1:RANK_BURST_SIZE], ICACHE_VICT_WAY}),
  .out(SB_DATA_WR_MASK_OUT_UNINVERTED)
);

inv1$   inv1$_DATA_WR_MASK_OUT[NUM_SETS*NUM_WAYS*RANK_BURST_SIZE-1:0](DATA_WR_MASK_OUT, DATA_WR_MASK_OUT_UNINVERTED);
inv1$   inv1$_SB_DATA_WR_MASK_OUT[NUM_SETS*NUM_WAYS*RANK_BURST_SIZE-1:0](SB_DATA_WR_MASK_OUT, SB_DATA_WR_MASK_OUT_UNINVERTED);

assign TAG_VALID_SET_INDEX  = ICACHE_PHYS_ADDR[RANK_BURST_SIZE+INDEX_WIDTH-1:RANK_BURST_SIZE];
decoder2_4$   decoder2_4$_TAG_WR_MASK_OUT(.SEL(ICACHE_VICT_WAY), .Y(TAG_WR_MASK_OUT), .YBAR());

assign VALID_WR_EN          = {ICACHE_PHYS_ADDR[RANK_BURST_SIZE+INDEX_WIDTH-1:RANK_BURST_SIZE], ICACHE_VICT_WAY};

endmodule