module ag_sig #(
    parameter AG_CONTROL_SIGS_WIDTH=69
)(
    input [AG_CONTROL_SIGS_WIDTH-1:0] ucode_sig,
    output [1:0] ldAB,
    output [1:0] dstA_size,
    output [1:0] dstB_size,
    output [2:0] ldREGS,
    output ldEFLAGS,
    output ldEIP,
    output ldCS,
    output alu_srcb_mux,
    output [1:0] shf_srcb_mux,
    output [2:0] eflags_mux,
    output [2:0] eip_mux,
    output [1:0] cs_mux,
    output [1:0] mmx_op,
    output [2:0] alu_op,
    output shf_op,
    output movs0,
    output movs1,
    output cmps0,
    output cmps1,
    output cmps2,
    output [1:0] con_jmp,
    output cmpxchg,
    output cmovc,
    output [3:0] gp_dsta_mux,
    output [2:0] gp_dstb_mux,
    output seg_dst_mux,
    output [1:0] mm_dst_mux,
    output [3:0] store_data_mux,
    output [1:0] rw,
    output [1:0] ds,
    output [1:0] mem_ds,
    output [1:0] imm_mux,
    output [1:0] addr_mux,
    output stack_push,
    output intex,
    output ret_with_imm,
    output rm, 
    output op_ovr,
    output palu_size,
    output sbb_dir,
    output iret0,
    output [11:0] AG_FW_CONTROL_SIGS,
    output [11:0] MEM_FW_CONTROL_SIGS,
    output [11:0] EX_FW_CONTROL_SIGS
); 
    assign {ldAB, dstA_size, dstB_size, ldREGS, ldEFLAGS,
            ldEIP, ldCS, alu_srcb_mux, shf_srcb_mux, eflags_mux, eip_mux, cs_mux,
            mmx_op, alu_op, shf_op, movs0, movs1, cmps0, cmps1, cmps2, con_jmp, cmpxchg, cmovc,
            gp_dsta_mux, gp_dstb_mux, seg_dst_mux, mm_dst_mux, store_data_mux, rw, ds,
            mem_ds, imm_mux, addr_mux, stack_push, intex, ret_with_imm, rm, op_ovr, palu_size, sbb_dir, iret0,
            AG_FW_CONTROL_SIGS, MEM_FW_CONTROL_SIGS, EX_FW_CONTROL_SIGS} = ucode_sig;
endmodule