module ag_sig(
    input [52:0] ucode_sig,
    output [1:0] ldAB,
    output [1:0] dstA_size,
    output [1:0] dstB_size,
    output [2:0] ldREGS,
    output ldEFLAGS,
    output ldEIP,
    output ldCS,
    output alu_srcb_mux,
    output [1:0] shf_srcb_mux,
    output [2:0] eflags_mux,
    output [2:0] eip_mux,
    output [1:0] cs_mux,
    output [1:0] mmx_op,
    output [2:0] alu_op,
    output shf_op,
    output cmps,
    output [1:0] con_jmp,
    output cmpxchg,
    output cmovc,
    output [3:0] gp_dsta_mux,
    output [2:0] gp_dstb_mux,
    output seg_dst_mux,
    output [1:0] mm_dst_mux,
    output [3:0] store_data_mux,
    output [1:0] rw,
    output [1:0] ds
); 
    assign {ldAB, dstA_size, dstB_size, ldREGS, ldEFLAGS,
            ldEIP, ldCS, alu_srcb_mux, shf_srcb_mux, eflags_mux, eip_mux, cs_mux,
            mmx_op, alu_op, shf_op, cmps, con_jmp, cmpxchg, cmovc,
            gp_dsta_mux, gp_dstb_mux, seg_dst_mux, mm_dst_mux, store_data_mux, rw, ds} = ucode_sig;
endmodule