`timescale 1ns / 1ps

module tb_exhaustive_decoder();

    // --------------------------------------------------------
    // 1. Inputs to UUT
    // --------------------------------------------------------
    reg [127:0] cache_line;

    // --------------------------------------------------------
    // 2. Outputs from UUT
    // --------------------------------------------------------
    wire prefix_rep;
    wire prefix_op_size;
    wire [2:0] prefix_seg_ov_id;
    wire prefix_ext;
    wire [7:0] opcode;
    wire [7:0] modrm;
    wire modrm_v;
    wire [7:0] sib;
    wire [1:0] disp_size_mux;
    wire [31:0] disp;
    wire [2:0] imm_size;
    wire [47:0] imm;
    wire [1:0] addressing_mode;
    wire [3:0] instr_length;

    // --------------------------------------------------------
    // 3. Instantiate UUT (block_decoder)
    // --------------------------------------------------------
    block_decoder uut (
        .cache_line(cache_line),
        .prefix_rep(prefix_rep),
        .prefix_op_size(prefix_op_size),
        .prefix_seg_ov_id(prefix_seg_ov_id),
        .prefix_ext(prefix_ext),
        .opcode(opcode),
        .modrm(modrm),
        .modrm_v(modrm_v),
        .sib(sib),
        .disp_size_mux(disp_size_mux),
        .disp(disp),
        .imm_size(imm_size),
        .imm(imm),
        .addressing_mode(addressing_mode),
        .instr_length(instr_length)
    );

    // --------------------------------------------------------
    // 4. File I/O and Test Tracking Variables
    // --------------------------------------------------------
    integer file, r;
    
    // FIXED: Upgraded to 32-bit integers to prevent %x memory overflow corruption
    integer exp_len;
    integer exp_opsize, exp_rep, exp_ext, exp_modrm_v;
    integer exp_opcode, exp_modrm, exp_sib;
    
    // FIXED: Flattened the array so older Verilog compilers don't crash on fscanf
    integer b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15; 

    integer test_count = 0;
    integer FAILURES = 0;
    integer SUCCESSES = 0;

    // --------------------------------------------------------
    // 5. Main Test Loop
    // --------------------------------------------------------
    initial begin
        $dumpfile("exhaustive_decoder_tb.vpd");
        $dumpvars(0, tb_exhaustive_decoder);

        $display("========================================");
        $display("  STARTING PILLAR 1 EXHAUSTIVE SWEEP    ");
        $display("========================================");
        
        // Open the file generated by the expanded Python script
        file = $fopen("../pillar1_tests.hex", "r");
        if (file == 0) begin
            $display("❌ ERROR: Could not open pillar1_tests.hex!");
            $display("Make sure you ran the Python script first and the file is one directory above the simulation directory.");
            $finish;
        end

        // Loop until end of file
        while (!$feof(file)) begin
            // Read 24 hex values per line (8 expected vals + 16 cache line bytes)
            r = $fscanf(file, "%x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x %x\n",
                        exp_len, exp_opsize, exp_rep, exp_ext, exp_opcode, exp_modrm_v, exp_modrm, exp_sib,
                        b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15);

            // FIXED: Only process if we read exactly 24 items (Prevents blank EOF line crashes)
            if (r == 24) begin
                
                // Pack the explicit bytes into the 128-bit cache_line vector.
                // Truncating the integers to [7:0] ensures clean assignment.
                cache_line = {b15[7:0], b14[7:0], b13[7:0], b12[7:0], b11[7:0], b10[7:0], b9[7:0], b8[7:0],
                              b7[7:0], b6[7:0], b5[7:0], b4[7:0], b3[7:0], b2[7:0], b1[7:0], b0[7:0]};

                #15; // Wait 15ns for the combinational decoder logic to fully settle
                
                test_count = test_count + 1;

                // Self-Checking Assertions (Using bit-slicing to safely extract the 1-bit/8-bit values from the integers)
                if (instr_length !== exp_len[3:0] || 
                    opcode !== exp_opcode[7:0] || 
                    modrm_v !== exp_modrm_v[0] || 
                    (exp_modrm_v[0] && modrm !== exp_modrm[7:0]) || 
                    prefix_op_size !== exp_opsize[0] || 
                    prefix_rep !== exp_rep[0] ||
                    prefix_ext !== exp_ext[0]) begin
                    
                    $display("❌ FAIL [Test %0d]", test_count);
                    $display("   EXPECTED: Len=%0d OpSize=%b Rep=%b Ext=%b Op=%h ModV=%b ModRM=%h", 
                             exp_len[3:0], exp_opsize[0], exp_rep[0], exp_ext[0], exp_opcode[7:0], exp_modrm_v[0], exp_modrm[7:0]);
                    $display("   ACTUAL  : Len=%0d OpSize=%b Rep=%b Ext=%b Op=%h ModV=%b ModRM=%h", 
                             instr_length, prefix_op_size, prefix_rep, prefix_ext, opcode, modrm_v, modrm);
                    $display("   DEBUG   : disp_size_mux=%b, imm_size=%b, sib=%h", disp_size_mux, imm_size, sib);
                    FAILURES = FAILURES + 1;
                end
                else begin
                    // Optional: Comment this out if thousands of lines of "PASS" clutters your console
                    $display("✅ PASS [Test %0d]", test_count);
                    SUCCESSES = SUCCESSES + 1;
                end
            end
        end

        $fclose(file);
        
        $display("========================================");
        $display("        EXHAUSTIVE SWEEP COMPLETE       ");
        $display("  Ran %0d tests.", test_count);
        if (FAILURES == 0) begin
            $display("  ✅ ALL TESTS PASSED! ZERO FAILURES!");
        end else begin
            $display("  ❌ FAILED %0d TESTS.", FAILURES);
        end
        $display("========================================");
        $display("FAILURES = %d out of %d\n", FAILURES, FAILURES + SUCCESSES);
        $display("SUCCESSES = %d out of %d\n", SUCCESSES, FAILURES + SUCCESSES);
        $finish;
    end

endmodule