module mem_to_ex(
    input clk,
    input rst_n,
    input we,

    input [55:0]     from_mem_control_sigs,
    input [2:0]      from_mem_dstidA,
    input [2:0]      from_mem_dstidB,
    input [31:0]     from_mem_srcregA,
    input [31:0]     from_mem_srcregB,
    input [31:0]     from_mem_srcregC,
    input [15:0]     from_mem_srcSREG,
    input [63:0]     from_mem_MMA,
    input [63:0]     from_mem_MMB,

    input [15:0]     from_mem_target_cs,
    input [63:0]     from_mem_load_result,
    input [31:0]     from_mem_inc_esp,
    input [31:0]     from_mem_dec_esp,
    input [31:0]     from_mem_imm,
    input [31:0]     from_mem_rel_eip,

    input            from_mem_store_is_io_line_0,
    input [14:4]     from_mem_store_addr_line_0,
    input [15:0]     from_mem_store_mask_line_0,
    input            from_mem_store_queue_alloc_line_0,
    input [14:4]     from_mem_store_addr_line_1,
    input [15:0]     from_mem_store_mask_line_1,
    input            from_mem_store_queue_alloc_line_1,
    input [4:0]      from_mem_store_data_shf_amt,
 
    input [15:0]     from_mem_cs,
    input [31:0]     from_mem_oeip,
    input [31:0]     from_mem_ieip,
    input [31:0]     from_mem_pred_eip,
    input [1:0]      from_mem_exception,
    input            from_mem_valid,
    
    output [55:0]    to_ex_control_sigs,
    output [2:0]     to_ex_dstidA,
    output [2:0]     to_ex_dstidB,
    output [31:0]    to_ex_srcregA,
    output [31:0]    to_ex_srcregB,
    output [31:0]    to_ex_srcregC,
    output [15:0]    to_ex_srcSREG,
    output [63:0]    to_ex_MMA,
    output [63:0]    to_ex_MMB,

    output [15:0]    to_ex_target_cs,
    output [63:0]    to_ex_load_result,
    output [31:0]    to_ex_inc_esp,
    output [31:0]    to_ex_dec_esp,
    output [31:0]    to_ex_imm,
    output [31:0]    to_ex_rel_eip,

    output           to_ex_store_is_io_line_0,
    output [14:4]    to_ex_store_addr_line_0,
    output [15:0]    to_ex_store_mask_line_0,
    output           to_ex_store_queue_alloc_line_0,
    output [14:4]    to_ex_store_addr_line_1,
    output [15:0]    to_ex_store_mask_line_1,
    output           to_ex_store_queue_alloc_line_1,
    output [4:0]     to_ex_store_data_shf_amt,

    output [15:0]    to_ex_cs,
    output [31:0]    to_ex_oeip,
    output [31:0]    to_ex_ieip,
    output [31:0]    to_ex_pred_eip,
    output [1:0]     to_ex_exception,
    output           to_ex_valid
);

    wire [686:0] reg_din, reg_q, reg_qb;
    assign reg_din = {from_mem_control_sigs, 
                      from_mem_dstidA, 
                      from_mem_dstidB, 
                      from_mem_srcregA, 
                      from_mem_srcregB, 
                      from_mem_srcregC, 
                      from_mem_srcSREG, 
                      from_mem_MMA, 
                      from_mem_MMB, 
                      from_mem_target_cs,
                      from_mem_load_result,
                      from_mem_inc_esp, 
                      from_mem_dec_esp, 
                      from_mem_imm, 
                      from_mem_rel_eip, 
                      from_mem_store_is_io_line_0,
                      from_mem_store_addr_line_0,
                      from_mem_store_mask_line_0,
                      from_mem_store_queue_alloc_line_0,
                      from_mem_store_addr_line_1,
                      from_mem_store_mask_line_1,
                      from_mem_store_queue_alloc_line_1,
                      from_mem_store_data_shf_amt,
                      from_mem_cs, 
                      from_mem_oeip, 
                      from_mem_ieip, 
                      from_mem_pred_eip,
                      from_mem_exception,
                      from_mem_valid};
    assign {to_ex_control_sigs, 
            to_ex_dstidA, 
            to_ex_dstidB, 
            to_ex_srcregA, 
            to_ex_srcregB, 
            to_ex_srcregC, 
            to_ex_srcSREG, 
            to_ex_MMA, 
            to_ex_MMB, 
            to_ex_target_cs,
            to_ex_load_result,
            to_ex_inc_esp, 
            to_ex_dec_esp, 
            to_ex_imm, 
            to_ex_rel_eip, 
            to_ex_store_is_io_line_0,
            to_ex_store_addr_line_0,
            to_ex_store_mask_line_0,
            to_ex_store_queue_alloc_line_0,
            to_ex_store_addr_line_1,
            to_ex_store_mask_line_1,
            to_ex_store_queue_alloc_line_1,
            to_ex_store_data_shf_amt,
            to_ex_cs, 
            to_ex_oeip, 
            to_ex_ieip, 
            to_ex_pred_eip,
            to_ex_exception,
            to_ex_valid} = reg_q;
    reg_mem_to_ex reg_mem_to_ex_inst(clk, reg_din, reg_q, reg_qb, rst_n, 1'b1, we);

endmodule